/* eslint-disable */
/**
 * This file was generated by 'vite-plugin-kit-routes'
 *
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
const PAGES = {
  "/": `/`,
  "/admin": `/admin`,
  "/admin/login": `/admin/login`,
  "/admin/logout": `/admin/logout`,
  "/admin/newsletter": `/admin/newsletter`,
  "/[slug]": (params: { slug: (string | number) }) => {
    return `/${params['slug']}`
  },
  "/archiv": `/archiv`,
  "/nastroje/preklady-prevod-textu": `/nastroje/preklady-prevod-textu`,
  "/nastroje/prevod-svg": `/nastroje/prevod-svg`,
  "/nastroje/svg-editor": `/nastroje/svg-editor`,
  "/nastroje/vypocet-procent-sloupcu": `/nastroje/vypocet-procent-sloupcu`,
  "/preview/[slug]": (params: { slug: (string | number) }) => {
    return `/preview/${params['slug']}`
  }
}

/**
 * SERVERS
 */
const SERVERS = {
  "prerender /algolia": `/algolia`,
  "GET /algolia": `/algolia`,
  "POST /api/git-commit": `/api/git-commit`,
  "GET /api/images/[slug]": (params: { slug: (string | number) }) => {
    return `/api/images/${params['slug']}`
  },
  "POST /api/newsletter/subscribe": `/api/newsletter/subscribe`,
  "prerender /api/og": `/api/og`,
  "GET /api/og": `/api/og`,
  "prerender /api/og/preview": `/api/og/preview`,
  "GET /api/og/preview": `/api/og/preview`,
  "POST /api/upload": `/api/upload`,
  "GET /preview/files/article/[slug]": (params: { slug: (string | number) }) => {
    return `/preview/files/article/${params['slug']}`
  },
  "prerender /rss": `/rss`,
  "GET /rss": `/rss`,
  "prerender /sitemap.xml": `/sitemap.xml`,
  "GET /sitemap.xml": `/sitemap.xml`
}

/**
 * ACTIONS
 */
const ACTIONS = {
  "default /admin/login": `/admin/login`,
  "default /admin/logout": `/admin/logout`
}

/**
 * LINKS
 */
const LINKS = {
  
}

type ParamValue = string | number | boolean | null | undefined

/**
 * Append search params to a string
 */
export const appendSp = (
  sp?: Record<string, ParamValue | ParamValue[]>,
  prefix: '?' | '&' = '?',
) => {
  if (sp === undefined) return ''

  const params = new URLSearchParams()
  const append = (n: string, v: ParamValue) => {
    if (v !== undefined) {
      params.append(n, String(v))
    }
  }

  let anchor = ''
  for (const [name, val] of Object.entries(sp)) {
    if (name === '__KIT_ROUTES_ANCHOR__' && val !== undefined) {
      anchor = `#${val}`
      continue
    }
    if (Array.isArray(val)) {
      for (const v of val) {
        append(name, v)
      }
    } else {
      append(name, val)
    }
  }

  const formatted = params.toString()
  if (formatted || anchor) {
    return `${prefix}${formatted}${anchor}`.replace('?#', '#')
  }
  return ''
}

/**
 * get the current search params
 * 
 * Could be use like this:
 * ```
 * route("/cities", { page: 2 }, { ...currentSP() })
 * ```
 */ 
export const currentSp = () => {
  const params = new URLSearchParams(window.location.search)
  const record: Record<string, string> = {}
  for (const [key, value] of params.entries()) {
    record[key] = value
  }
  return record
}

/* type helpers for route function */
type NonFunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T]
type FunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T]
type FunctionParams<T> = T extends (...args: infer P) => any ? P : never

const AllObjs = { ...PAGES, ...ACTIONS, ...SERVERS, ...LINKS }
type AllTypes = typeof AllObjs

export type Routes = keyof AllTypes extends `${string}/${infer Route}` ? `/${Route}` : keyof AllTypes
export const routes = [
	...new Set(Object.keys(AllObjs).map((route) => /^\/.*|[^ ]?\/.*$/.exec(route)?.[0] ?? route)),
] as Routes[]

/**
 * To be used like this: 
 * ```ts
 * import { route } from './ROUTES'
 * 
 * route('site_id', { id: 1 })
 * ```
 */
export function route<T extends FunctionKeys<AllTypes>>(key: T, ...params: FunctionParams<AllTypes[T]>): string
export function route<T extends NonFunctionKeys<AllTypes>>(key: T): string
export function route<T extends keyof AllTypes>(key: T, ...params: any[]): string {
  if (AllObjs[key] as any instanceof Function) {
    const element = (AllObjs as any)[key] as (...args: any[]) => string
    return element(...params)
  } else {
    return AllObjs[key] as string
  }
}

/**
* Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
*
* Full example:
* ```ts
* import type { KIT_ROUTES } from '$lib/ROUTES'
* import { kitRoutes } from 'vite-plugin-kit-routes'
*
* kitRoutes<KIT_ROUTES>({
*  PAGES: {
*    // here, key of object will be typed!
*  }
* })
* ```
*/
export type KIT_ROUTES = {
  PAGES: { '/': never, '/admin': never, '/admin/login': never, '/admin/logout': never, '/admin/newsletter': never, '/[slug]': 'slug', '/archiv': never, '/nastroje/preklady-prevod-textu': never, '/nastroje/prevod-svg': never, '/nastroje/svg-editor': never, '/nastroje/vypocet-procent-sloupcu': never, '/preview/[slug]': 'slug' }
  SERVERS: { 'prerender /algolia': never, 'GET /algolia': never, 'POST /api/git-commit': never, 'GET /api/images/[slug]': 'slug', 'POST /api/newsletter/subscribe': never, 'prerender /api/og': never, 'GET /api/og': never, 'prerender /api/og/preview': never, 'GET /api/og/preview': never, 'POST /api/upload': never, 'GET /preview/files/article/[slug]': 'slug', 'prerender /rss': never, 'GET /rss': never, 'prerender /sitemap.xml': never, 'GET /sitemap.xml': never }
  ACTIONS: { 'default /admin/login': never, 'default /admin/logout': never }
  LINKS: Record<string, never>
  Params: { 'slug': never }
}
