name: 'Setup Node.js with pnpm'
description: 'Setup pnpm, Node.js, and install dependencies'

inputs:
  setup-env:
    description: 'Copy .env.example to .env'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Setup environment
      if: inputs.setup-env == 'true'
      shell: bash
      run: cp .env.example .env
